repos:

  - repo: local
    hooks:

      - id: eslint
        name: eslint
        entry: eslint
        language: node
        types_or:
          - javascript
        additional_dependencies:
          - "@eslint/js@9.39.1"
          - "@stylistic/eslint-plugin@5.6.1"
          - eslint@9.39.1
          - globals@16.3.0

      - id: web-ext lint
        name: web-ext lint
        entry: web-ext lint
        language: node
        types_or:
          - javascript
        pass_filenames: false
        additional_dependencies:
          - web-ext@8.9.0

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.4.0
    hooks:
      - id: editorconfig-checker
        exclude: (browser-polyfill.js|.*.fodg)
